### ISSUE TITLE
Removed bank code 3020 still present

### ISSUE THREAD

**Issue by janedbal** [heureka/bank-account-validator#2]
According to [linked document](http://www.cnb.cz/cs/platebni_styk/ucty_kody_bank/download/kody_bank_CR.pdf), Meinl bank (3020) was removed, shouldn't it be removed from this library too?

It would be nice to have some (semi)automatic update :)

---

EDIT: oh, latest version is 170 ([link](https://www.cnb.cz/cs/platebni_styk/ucty_kody_bank/)) so bank code 3050 should be added too

**Comment by janedbal** [comment]
Thank you

**Comment by janjelinek** [comment]
Thanks for your issue. I'll try think about automatic check for new bank codes list, but without API from ČNB is not easy :/

**Comment by janedbal** [comment]
@jannavratil I think it is possible. I guess that current valid list of all bank codes is on URL https://www.cnb.cz/cs/platebni_styk/ucty_kody_bank/download/kody_bank_CR.csv (which is quite ok for parsing). [Future](https://www.cnb.cz/cs/platebni_styk/ucty_kody_bank/download/kody_bank_CR_170.csv) and [old codes](https://www.cnb.cz/cs/platebni_styk/ucty_kody_bank/historicke_ciselniky.html) uses URL with suffix like `_168`.

We will see 1.4.2016 if version 170 will be available on "stable" URL and 169 will become suffixed.

**Comment by janedbal** [comment]
It seems to be exactly as I mentioned...

**Comment by heureka** [comment]
Nice to see. I prepare some check service.
