### ISSUE TITLE
New version of bank codes

### ISSUE THREAD

**Issue by janedbal** [heureka/bank-account-validator#4]
Today, ČNB released [version 171](https://www.cnb.cz/cs/platebni_styk/ucty_kody_bank/download/kody_bank_CR.pdf). List of bank codes should be updated :)

**Comment by janedbal** [comment]
It seems that updates are pretty often. Now, version 172 is available...

**Comment by janjelinek** [comment]
What about this: https://github.com/heureka/bank-account-validator/pull/5
